### ISSUE TITLE
Add HypothesisTest to run Diagnostics

### ISSUE THREAD

**Issue by guilhermebodin** [LAMPSPUC/StateSpaceModels.jl#114]
Should we consider using HypothesisTests instead of creating our own version? This could be at least on the tests to assure we are doing the right thing.

**Comment by raphaelsaavedra** [comment]
HypothesisTests.jl doesn't have the homoscedasticity test, so we'd need to implement at least one, I think it's fine to leave as it is. However I think it's a good idea to use the package in the tests to confirm our p-values for Jarque-Bera and Ljung-Box.

**Comment by guilhermebodin** [comment]
We could do that and more, maybe you could make a PR on HypothesisTests.jl

**Comment by raphaelsaavedra** [comment]
I'll try to do that

**Comment by raphaelsaavedra** [comment]
Opened it in https://github.com/JuliaStats/HypothesisTests.jl/pull/167

**Comment by raphaelsaavedra** [comment]
This was added to HypothesisTests (https://github.com/JuliaStats/HypothesisTests.jl/pull/167 and https://github.com/JuliaStats/HypothesisTests.jl/pull/169) so it can be done now
