### ISSUE TITLE
Conflicting method definition

### ISSUE THREAD

**Issue by appleparan** [LAMPSPUC/StateSpaceModels.jl#143]
Following method definition conflict occur. 

```
Method definition vec(Number) in module FiniteDiff at /home/appleparan/.julia/packages/FiniteDiff/IPtYL/src/jacobians.jl:128 overwritten in module DiffEqDiffTools at /home/appleparan/.julia/packages/DiffEqDiffTools/3mm8U/src/jacobians.jl:114.
  ** incremental compilation may be fatally broken for this module **
```
It seems `Optim` package version limit in `Project.toml` makes this warning. Is there a reason keeping version limit in `Project.toml`?

PS: here is a dependencies of problematic packages.
* `Optim` -> `NLSolversBase` -> `FiniteDiff` 
* `Optim` -> `DiffEqDiffTools`

**Comment by raphaelsaavedra** [comment]
Hi! Thank you for opening the issue. Yes, I believe updating Optim's version should solve that.

Can you point out what causes that warning to pop up? I tried running some basic tests and it didn't show up.

**Comment by appleparan** [comment]
I just installed `StateSpaceModel` today and Optim has downgraded and ` DiffEqDiffTools ` also installed (that's real reason I got that warning), then I found [this](https://www.reddit.com/r/Julia/comments/ev8hdr/anyone_else_encountering_this_warning/) 
I feel updating `Optim` will solve the problem.

Here is my log for installing `StateSpaceModel`

```
(Mise) pkg> add StateSpaceModels
 Resolving package versions...
 Installed StateSpaceModels ─ v0.3.1
  Updating `~/src/Mise.jl/Project.toml`
  [99342f36] + StateSpaceModels v0.3.1
  Updating `~/src/Mise.jl/Manifest.toml`
  [49dc2e85] + Calculus v0.5.1
  [01453d9d] + DiffEqDiffTools v1.7.0
  [429524aa] ↓ Optim v0.20.1 ⇒ v0.19.7
  [99342f36] + StateSpaceModels v0.3.1
```
