### ISSUE TITLE
possible test failure in upcoming Julia version 1.5

### ISSUE THREAD

**Issue by rfourquet** [LAMPSPUC/StateSpaceModels.jl#155]
A PkgEval run for a [PR](https://github.com/JuliaLang/julia/pull/35078) which changes the generated numbers for `randn!` indicates that the tests of this package might fail in Julia 1.5 (and on Julia current master). Apologies if this is a false positive.
cf. https://github.com/JuliaCI/NanosoldierReports/blob/7de24e455342298cbef56826b5827f0d7640d2c1/pkgeval/by_hash/b89e35c_vs_098ef24/logs/StateSpaceModels/1.5.0-DEV-71a4a114c2.log

**Comment by raphaelsaavedra** [comment]
Hi @rfourquet,

Thanks for the heads up. This is a good reminder to us that we are a little late in our CI checks. We are currently testing only up to 1.3, we definitely should be testing 1.4 and nightly (allowing failures on nightly).

That error also shows that our tests are not that robust if they are depending on a certain seed :) We will look into it.
