### ISSUE TITLE
Add Plot recipes for forecasting and components

### ISSUE THREAD

**Issue by guilhermebodin** [LAMPSPUC/StateSpaceModels.jl#170]
Here we could create another abstraction such as an UnobservedComponentsModel where we should give a name to each component

**Comment by raphaelsaavedra** [comment]
IMO this doesn't need to be part of the 0.4 milestones, I think the main requirement for releasing 0.4 is that there are no significant downgrades. New stuff can be added after we merge the refactor branch so that we don't postpone the merge for too long.
