### ISSUE TITLE
Add and test an example with Cycles

### ISSUE THREAD

**Issue by guilhermebodin** [LAMPSPUC/StateSpaceModels.jl#171]
We should see on stamp if there is a classic dataset that uses Cycles and write the model, some forecasting and the tests

**Comment by raphaelsaavedra** [comment]
IMO this doesn't need to be part of the 0.4 milestones, I think the main requirement for releasing 0.4 is that there are no significant downgrades. New stuff can be added after we merge the refactor branch so that we don't postpone the merge for too long.

**Comment by guilhermebodin** [comment]
I think this one should be before 0.4 to guarantee that there are no tricks needed to do this

**Comment by guilhermebodin** [comment]
We have `LocalLevelCycle` from #174
