### ISSUE TITLE
Major to do's for 0.4

### ISSUE THREAD

**Issue by raphaelsaavedra** [LAMPSPUC/StateSpaceModels.jl#178]
- [x] **Refactor how `fit` works.**
`x = fit(model)` returns the loglikelihood and stores the estimated parameters inside `model`, so it should be `fit!(model)` since it mutates `model`. Still, that raises another issue, which is that there's something returned that is not stored, so we can't just have `fit!(model)` rather than `llk = fit!(model)` which is really ugly. IMO `fit!(model)` should already store the estimation stats within `model`. 
Another advantage of renaming to `fit!` is that it stops conflicting with `Distributions.fit` (we don't have Distributions as a dep, but it's reasonable to assume people will often have it loaded when using statistical / time series packages).
 - [ ] **Add missing docstring for all exported functions.**
 There are lots of missing docstrings which makes it hard to use the package.  At least all the exported functions should have a nice docstring.
- [x] **Add examples.**
We should have example scripts in an `examples/` folder, possibly the same ones that we have in the master, as well as some documentation explaining these examples. **Examples should be in the docs**

**Comment by guilhermebodin** [comment]
About the examples, I would say that the documentation should be enough.

**Comment by guilhermebodin** [comment]
The `fit!` function should be reaady on #187
