### ISSUE TITLE
Update optimization dependency

### ISSUE THREAD

**Issue by rmendels** [LAMPSPUC/StateSpaceModels.jl#181]
First thanks for working on this package,  I m very interested in using it.  But,  right now the Dependencies list:

Optim = "0.20"

while Optim is at version 1.1.0.    Any chance of getting this upgraded,  and updated in the package repository.

Also,  a selfish request,  adding both univariate processing and collapsed models to the multivariate models.

Thanks.

**Comment by guilhermebodin** [comment]
Upgrading the dependency is one of the tasks we must do to release version 0.4 #174 Univariate processing and collapsed models will probably be implemented after the refactoring. We still need to decide the priority list.

**Comment by rmendels** [comment]
@guilhermebodin  Thanks for the information.    Will track progress on this.

**Comment by raphaelsaavedra** [comment]
Hi @rmendels, due to JuliaNLSolvers/Optim.jl#863, Optim 1.0 and above are broken for Julia 1.0. Since that is still the LTS version, we are opting not to bump Optim to 1.x in the next release. After the 0.4 release, we plan to make a new release with the latest Optim version (this release will likely be restricted to Julia 1.2 and above) - see https://github.com/LAMPSPUC/StateSpaceModels.jl/pull/182

**Comment by rmendels** [comment]
@raphaelsaavedra  Thanks for the info.   Just FYI,  what I have is a complicated Dynamic factor model,  where I want to estimate the parameters of the observation matrix,  but it is not a simple map from parameters to observation matrix,  and the problem is very large,  thousands of series.  So I want to use collapsing,  which I can do if I can set up the model matrices,  feed it to some program to get the likelihood and then use Optim to get the results.  I actually have it programmed in R using KFAS,  but I need greater speed.  KFAS has a nice function where if you pass it the KFAS model structure it returns the likelihood.

**Comment by raphaelsaavedra** [comment]
I see. I believe that's what you refer to in https://github.com/LAMPSPUC/StateSpaceModels.jl/issues/185, right? That would definitely be a nice feature to have -- we already have that in 0.4 but I think the way to do it could be simpler and it should be easy to implement.

**Comment by rmendels** [comment]
@raphaelsaavedra   Yes,  the problem I described is the basis for both requests.  I understand you have a lot of work on your hands and have to set priorities,  and adding things just for one person can be  waste of time.  So if any of this gets implemented,  great,  if not I appreciate your work on this either way.
