### ISSUE TITLE
Discover how to evaluate p_values without Distributions.jl

### ISSUE THREAD

**Issue by guilhermebodin** [LAMPSPUC/StateSpaceModels.jl#186]
We might need Distributions.jl to evaluate p_values. It would be nice to not have Distributions as a dependecy.

**Comment by raphaelsaavedra** [comment]
It's always good to have fewer dependencies, but I think Distributions.jl is fine - I think it will be helpful for the multivariate cases as well due to `MvNormal`

**Comment by guilhermebodin** [comment]
In the multivariate cases we can just do `cholesky(H) * randn(size(H, 1))`

**Comment by guilhermebodin** [comment]
We will need other things like quantile... I think you are right, Distributions is fine, it is too much work not having it.
