### ISSUE TITLE
Error with structural model and single precision

### ISSUE THREAD

**Issue by juliohm** [LAMPSPUC/StateSpaceModels.jl#195]
To reproduce the error:

```Julia
julia> using StateSpaceModels
julia> structural(rand(Float32, 100), 10)
ERROR: MethodError: no method matching StateSpaceModel(::Array{Float32,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2})
Closest candidates are:
  StateSpaceModel(::Union{Array{Typ,1}, Array{Typ,2}}, ::Array{Typ,3}, ::Array{Typ,2}, ::Array{Typ,2}) where Typ<:Real at /u/juliohm/.julia/packages/StateSpaceModels/VzSgw/src/structures.jl:141
  StateSpaceModel(::Union{Array{Typ,1}, Array{Typ,2}}, ::Array{Typ,3}, ::Array{Typ,2}, ::Array{Typ,2}, ::Array{Typ,2}, ::Array{Typ,2}, ::Array{Typ,2}, ::Array{Typ,2}) where Typ<:Real at /u/juliohm/.julia/packages/StateSpaceModels/VzSgw/src/structures.jl:116
  StateSpaceModel(::Union{Array{Typ,1}, Array{Typ,2}}, ::Array{Typ,2}, ::Array{Typ,2}, ::Array{Typ,2}) where Typ<:Real at /u/juliohm/.julia/packages/StateSpaceModels/VzSgw/src/structures.jl:157
```

Some of the intermediate matrices passed to the `StateSpaceModel` in the `structural` helper function are being converted to double precision somewhere.

**Comment by raphaelsaavedra** [comment]
Hey @juliohm, thanks for raising this :) 

I think I know what the issue is and it's pretty simple. This code is getting refactored but I'll open a PR to see if I can quickly fix it.

**Comment by guilhermebodin** [comment]
@juliohm Just out of curiosity, what is the application that requires a single precision?

**Comment by juliohm** [comment]
@guilhermebodin it just that we are loading a bunch of climate date for the globe and have a time series for each lat/lon. Because we want to save memory and possibly move some computation to the GPU, we decided to save in single precision. Currently I am just converting back to double precision inside the state space helper function before fitting a structural model.

**Comment by juliohm** [comment]
Thanks for sharing these tips. I will see how I can choose a different filter and initialization as suggested.

**Comment by raphaelsaavedra** [comment]
Exact initialization is still not implemented. You can try to use the square-root filter as it is pretty straightforward, just keep in mind that the tradeoff for stability is sacrificing some performance. We are now also keeping an eye out for single precision issues in the upcoming 0.4.

**Comment by juliohm** [comment]
Closing as too old. MWE no longer valid.
