### ISSUE TITLE
Lead-time forecasting

### ISSUE THREAD

**Issue by juliohm** [LAMPSPUC/StateSpaceModels.jl#198]
Given `p` steps from the past, a present time `t`, and `f` steps into the future, the state-space model forecast produces the full time series from `t+1` until `t+f` after training from `t-p-1` to `t`. This is sometimes called "single-shot" forecasting.

I wonder if there is a performance trick that would allow us to train the model on `t-p-1` to `t` to predict just the next step `t+1`, then advance time, and "retrain" the model with a warm start on `t-p` to `t+1` to predict `t+2`? This is sometimes called "1-lead" forecasting. More generally, "n-lead" forecasting consists of sliding time `n` steps, and retraining the model as the data becomes available.

Please ignore the issue if it doesn't make sense. I am trying to compare the results I got so far with other models that are more greedy in that sense.

**Comment by raphaelsaavedra** [comment]
If I understand correctly, the idea would just be to use the filter in an online application where you're always forecasting only one step ahead, observing the next realization of y, and then re-estimating the model with the same amount of data (i.e., removing the first observation).

I haven't personally looked into this application so I'm not aware of performance tricks, but defining a new model with the characteristics above and then setting the `seeds` (which are just the initial points of the optimization -- sorry, bad name) as the solution of the previous iteration should yield performance advantages by warm starting the problem. I think this would not be hard to implement just using the current version 0.3. 

Online implementations are definitely in our radar and we hopefully will have more stuff coming up in the future, although advances have been somewhat slow on our side recently.

**Comment by juliohm** [comment]
That is nice to hear. I am enjoying learning more about state space models and being able to experiment with the different structures using the package. Looking forward to the future releases.

P.S.: I know well what it means to be overloaded with different things on the TODO list :)

**Comment by guilhermebodin** [comment]
@raphaelsaavedra I think we should make a gist about it but I would not put a function that does the 1 step ahead forecasting and re-estimates in the package right now.

**Comment by guilhermebodin** [comment]
This is the main idea for doing this procedure
```julia
using StateSpaceModels, CSV, DataFrames
nile = CSV.read(StateSpaceModels.NILE, DataFrame)
for i in 1:10
    @show i
    y = nile.flow[1:80 + i]
    model = LocalLevel(y)
    # warm start
    if i > 2
        model.hyperparameters.constrained_values = estimated_params
    end
    fit!(model)
    forec = forecast(model, 1)
    estimated_params = model.results.coef_table.coef
end
```

**Comment by raphaelsaavedra** [comment]
I think that's pretty much it, the main difference being that it should be `i:80` -- if I understand correctly, it should be a rolling window. But yeah, unfortunately there aren't any clever performance tricks for this as of now other than setting the initial values of hyperparameters as the solution of the previous iteration (which should already be pretty helpful)
