### ISSUE TITLE
Change forecast result to just distributions?

### ISSUE THREAD

**Issue by juliohm** [LAMPSPUC/StateSpaceModels.jl#199]
I noticed that the forecast function returns `mean.(d), d`. What do you think of just returning the distribution `d`? and leave the statistic of interest to the user? I think it would be more elegant, and would make users think about what they are getting from the function.

**Comment by raphaelsaavedra** [comment]
I agree it's more elegant and honestly there are no downsides to this. Since it's a pretty straightforward change, could you open a PR about this?

**Comment by juliohm** [comment]
Nice. I will try to submit a PR by the end of the day 👍
