### ISSUE TITLE
Consider standardising the data internally

### ISSUE THREAD

**Issue by juliohm** [LAMPSPUC/StateSpaceModels.jl#206]
I've noticed that the results are sensitive to scaling. If we have a time series `z`, maybe it is good idea to operate on `(z .- mean(z)) ./ std(z)`, and undo the normalisation before returning? The results can be drastically different otherwise depending on the units chosen.

**Comment by guilhermebodin** [comment]
Actually I think the results become different because of the filter initialization. We use big kappa approximation for filter initialization but there is an algorithm that performs an exact initialization of the Kalman filter.

**Comment by juliohm** [comment]
Nice. Good to know the issue is in your radar already 👍

**Comment by guilhermebodin** [comment]
Closing because it is related to #60
