### ISSUE TITLE
Problem using Kalman Filter

### ISSUE THREAD

**Issue by ronb1000** [LAMPSPUC/StateSpaceModels.jl#243]
The Nile example works fine. When I replaced the Nile data with my data, the filter failed (Kalman and data were almost identical). I tried rounding my data to xxx.x and the Kalman worked. When I tried a larger datafile (700 entries) rounding did not help - the Kalman and data were again almost identical.  Am I doing something wrong or are there restrictions buried in implementation? Seems like a great package. I would like to get it to work with my data,

**Comment by guilhermebodin** [comment]
HI @ronb1000,  can you post the code and the data so I can try to help you better? I am always happy to help.

Depending on your data there might be initialization issues, in the filter we assume a diffuse initialization with a1 = 0 and P1 = 1e6.

**Comment by guilhermebodin** [comment]
@ronb1000 have you solved the issue?

**Comment by guilhermebodin** [comment]
Closing the issue for inactivity
