### ISSUE TITLE
performance question

### ISSUE THREAD

**Issue by waynelapierre** [LAMPSPUC/StateSpaceModels.jl#249]
My personal understanding is that estimating an ARIMA model is less computationally intensive than estimating a GARCH model. When I estimate an ARIMA model using StateSpaceModels.jl and a GARCH model using ARCHModels.jl with the same data, the former takes a much longer time. Is there any room for performance enhancement?

**Comment by guilhermebodin** [comment]
Could you provide the code? It depends on the approach towards estimation, and the code itself. 

In StateSpaceModels.jl there is room for improvement but it requires a somehow big refactor to use the automatic differentiation in the estimation process.

**Comment by waynelapierre** [comment]
I cannot share the data but the difference in time is so obvious so I believe you can try any data and find similar results. 

#arima(1, 0, 1) 
model1 = SARIMA(data.ret, order = (1, 0, 1))
StateSpaceModels.fit!(model1)

#garch(1, 1)
spec = GARCH{1, 1}([1.0, 0.9, 0.05])
model2 = UnivariateARCHModel(spec, data.ret, dist = StdT(3.0), meanspec = Intercept(1.0))
ARCHModels.fit!(model2)

**Comment by guilhermebodin** [comment]
Assuming that the time for instantiating the models is negligible indeed the estimation of the GARCH is faster. This can be due to many implementation details such as automatic differentiation on Optim, choosing good starting values etc.

```julia
julia> using BenchmarkTools

julia> @benchmark begin
           model = SARIMA(precos.comb_1; order = (1, 0, 1));
           StateSpaceModels.fit!(model);
       end
BenchmarkTools.Trial: 
  memory estimate:  1.64 MiB
  allocs estimate:  21104
  --------------
  minimum time:     9.730 ms (0.00% GC)
  median time:      10.499 ms (0.00% GC)
  mean time:        12.109 ms (3.85% GC)
  maximum time:     88.256 ms (8.83% GC)
  --------------
  samples:          413
  evals/sample:     1

julia> @benchmark begin
           spec = GARCH{1, 1}([1.0, 0.9, 0.05]);
           model2 = UnivariateARCHModel(spec, precos.comb_1, dist = StdT(3.0), meanspec = Intercept(1.0));
           ARCHModels.fit!(model2);
       end
BenchmarkTools.Trial: 
  memory estimate:  5.39 MiB
  allocs estimate:  14362
  --------------
  minimum time:     2.730 ms (0.00% GC)
  median time:      3.513 ms (0.00% GC)
  mean time:        5.142 ms (25.58% GC)
  maximum time:     104.535 ms (0.00% GC)
  --------------
  samples:          971
  evals/sample:     1
```
If you have a very specific kind of model you wish to estimate on StateSpaceModels you can define a custom filter to it. For instance the `LocalLevel` model has a specific filter, the `ScalarKalmanFilter`. This custom-made implementation can lead to a significant performance improvement, the downside is that it is not super simple to do so, you must have some knowledge about Kalman filters.

```julia
julia> @benchmark begin
         model = LocalLevel(precos.comb_1);
         StateSpaceModels.fit!(model);
     end
BenchmarkTools.Trial: 
  memory estimate:  81.75 KiB
  allocs estimate:  3383
  --------------
  minimum time:     854.142 μs (0.00% GC)
  median time:      898.010 μs (0.00% GC)
  mean time:        1.022 ms (1.72% GC)
  maximum time:     30.756 ms (0.00% GC)
  --------------
  samples:          4876
  evals/sample:     1

julia> @benchmark begin
           model = LocalLevel(precos.comb_1);
           a1 = zeros(Float64, 1)
           P1 = Float64.([1e6][:, :])
           filt = UnivariateKalmanFilter(a1, P1)
           StateSpaceModels.fit!(model; filter = filt);
     end
BenchmarkTools.Trial: 
  memory estimate:  119.13 KiB
  allocs estimate:  3929
  --------------
  minimum time:     5.750 ms (0.00% GC)
  median time:      5.993 ms (0.00% GC)
  mean time:        7.072 ms (0.30% GC)
  maximum time:     93.055 ms (0.00% GC)
  --------------
  samples:          707
  evals/sample:     1
```
