### ISSUE TITLE
get_smoothed_state performance issues for larger time series

### ISSUE THREAD

**Issue by mapi1** [LAMPSPUC/StateSpaceModels.jl#297]
I was adapting the Nile river example for time series of around 10.000 samples. 
Everything works fine and fast up to calling `get_smoothed_state()`  which does not finish and sometimes throws a StackOverflowError. I tested it on 1.6 and 1.7-rc3.

MWE:
```julia
using StateSpaceModels
N = 10000
signal = randn(N)
model = LocalLevel(signal)
# model = ExponentialSmoothing(signal) # As an example where the output is not a vector
fit!(model)
smoother_output = kalman_smoother(model)
get_smoothed_state(smoother_output)
``` 
The problem seems to be that calling `permutedims(cat(x..., dims = 2))` is somehow super slow compared to calling `permutedims(hcat(x...))`. Replacing this may be an easy fix, though I still don't understand why `cat` performs so badly or if I am missing anything here.

Otherwise, let me say thank you for this great package!

**Comment by raphaelsaavedra** [comment]
This is an interesting one. It seems `cat` can lead to some unreasonable times as you mentioned.

```julia
julia> x = randn(2000, 3);

julia> @time hcat(x...);
  0.000345 seconds (6.00 k allocations: 187.703 KiB)

julia> @time cat(x..., dims=2);
  2.501283 seconds (36.11 M allocations: 1.076 GiB, 40.25% gc time)
```

It also seems `vec(x)` is much faster than `x...` and achieves the same:

```julia
julia> @time permutedims(cat(vec(x), dims=2));
  0.000098 seconds (9 allocations: 94.047 KiB)
```

We should definitely fix that by using a faster alternative, thanks for bringing it to our attention!

**Comment by guilhermebodin** [comment]
Should be fixed in #298

**Comment by guilhermebodin** [comment]
@mapi1 please test in version 5.20

**Comment by mapi1** [comment]
Updated the package, works like a charm now. Thanks for the quick patch!
