### ISSUE TITLE
Allow Polynomials v2 in [compat]

### ISSUE THREAD

**Issue by mapi1** [LAMPSPUC/StateSpaceModels.jl#301]
When adding StateSpaceModels I noticed that some Pkgs (e.g. DSP) get downgraded. The cause is () the Polynomials v1 in the [compat] specification. I ran the tests with the latest version of Polynomials and there seemed to be no change. If this could be confirmed it would be nice to widen compatibility here. Breaking changes are documented [here](https://github.com/JuliaMath/Polynomials.jl/pull/310) in the case of a more rigorous check. 
Thanks again for this great package, it came in handy on several occasions already!

**Comment by raphaelsaavedra** [comment]
Thanks for letting us know – I have opened a PR, if we don't see anything breaking I think this looks safe to merge
