### ISSUE TITLE
Possible Issue with Std.Error in SARIMA()

### ISSUE THREAD

**Issue by dompazz** [LAMPSPUC/StateSpaceModels.jl#304]
I think you might have an issue with the standard error value in SARIMA
`
#AR1
#y_t = 1.0 + 0.5*y_t-1 + e, e ~ N(0,0.1)
n = 1000
burn_in = 50
y = Vector{Float64}(undef,n)

yt_last = 1.0
d = Normal(0,0.1)
e = rand(d,n+burn_in)

for i in 1:(n+burn_in)
    global yt_last
    y_t = 1.0 + 0.5*yt_last + e[i]
    yt_last = y_t
    if i > burn_in
        y[i-burn_in] = y_t
    end
end
println(@sprintf("Mean and Var of Y: %.2f, %.4f",mean(y),var(y)))
println(@sprintf("Expected values Y: %.2f, %.4f",2.0,.01/(1-.5^2)))

ar1 = SARIMA(y,order=(1,0,0),include_mean=true)
StateSpaceModels.fit!(ar1)
print_results(ar1)
`
This produces:

> Mean and Var of Y: 1.99, 0.0112
> Expected values Y: 2.00, 0.0133
>                              Results
> ===============================================================
> Model:                        SARIMA(1, 0, 0)x(0, 0, 0, 0) with non-zero mean
> Number of observations:       1000
> Number of unknown parameters: 3
> Log-likelihood:               943.0475
> AIC:                          -1880.0951
> AICc:                         -1880.0710
> BIC:                          -1865.3718
> ---------------------------------------------------------------
> Parameter      Estimate      Std.Error      z stat      p-value
> ar_L1            0.4538         1.2582      0.3607       0.9410
> mean             1.9913         0.1724     11.5524       0.0000
> sigma2_η         0.0089         0.0666      0.1329       0.0626

That ar_L1 Std.Error seems high (and the z-stat low given the known value).  Maybe it should be 1.2482/sqrt(1000), making the z-stat ~11.

**Comment by dompazz** [comment]
well none of that formatted well.... sorry

**Comment by guilhermebodin** [comment]
Thank you for pointing it out. Indeed I rechecked the calculations and we missed this division. I am opening a PR and releasing a new version
