### ISSUE TITLE
simulate_scenarios for BasicStructuralExplanatory fails if seasonality is not 12

### ISSUE THREAD

**Issue by SupplyChef** [LAMPSPUC/StateSpaceModels.jl#308]
A hard coded value of 14 in src\models\basicstructural_explanatory.jl line 201 assumes that the seasonality is 12. 

sys.Z[1][14:end] .= new_exogenous[1, :]

For models with a different seasonality, a dimension mismatch error is thrown (DimensionMismatch("array could not be broadcast to match destination"))

**Comment by guilhermebodin** [comment]
Hi @SupplyChef thanks for letting us know, I am fixing the issue and will release a new version.

**Comment by SupplyChef** [comment]
Thank you!
