### ISSUE TITLE
Can not fit MA(q)

### ISSUE THREAD

**Issue by shayandavoodii** [LAMPSPUC/StateSpaceModels.jl#323]
Hi, I want to fit an $MA(q)$ using this package. I saw your [documentation ](https://lost-stats.github.io/Time_Series/ARMA-models.html#julia) and tried to adjust it to get $MA(q)$ only. Here is what I tried and what I got:
```julia
julia> using StateSpaceModels

julia> ts = rand(100);

julia> model = SARIMA(ts, order=(0,0,2))
SARIMA(0, 0, 2)x(0, 0, 0, 0) with zero mean

julia> StateSpaceModel.fit!(model)
ERROR: type DataType has no field fit!
Stacktrace:
 [1] getproperty(x::Type, f::Symbol)
   @ Base .\Base.jl:32
 [2] top-level scope
   @ REPL[33]:1
```
How can I fit an $MA$ model on a vector?

**Comment by raphaelsaavedra** [comment]
Hi @shayandavoodii, that's actually an easy one – you have a typo on your `fit!` call. Note that you're calling `StateSpaceModel.fit!(model)`, not `StateSpaceModels.fit!(model)`. So you're trying to access a `fit` field in the type `StateSpaceModel`, which doesn't exist. The error message gives you a clue :)

**Comment by shayandavoodii** [comment]
Sorry, I was having dinner. Yes, you're right. I forgot to put the answer on my own. Thank you so much.
Considering the $MA(q)$ formulation:
$$X_t = \mu + \sum_{i=1}^{q} \theta_i \varepsilon_{t-i}$$
How can I get the coefficients? There are many attributes.
```julia
julia> using StateSpaceModels

julia> ts = rand(100);

julia> model = SARIMA(ts, order=(0,0,2))
SARIMA(0, 0, 2)x(0, 0, 0, 0) with zero mean

julia> res = StateSpaceModels.fit!(model)
SARIMA(0, 0, 2)x(0, 0, 0, 0) with zero mean
```
Does the following code give me the coefficients?
```julia
julia> res.results.coef_table.coef
3-element Vector{Float64}:
 0.5778745695380242
 0.36309170005361113
 0.17571266972630697
```
If yes, what's the order of them? I mean, does the first one represent $\theta_1$ for example?

**Comment by raphaelsaavedra** [comment]
The coefficient table also has a `names` field to help you identify which is which (the indices will be the same across `names` and `coefs`):

```julia
julia> model.results.coef_table.names
3-element Vector{String}:
 "ma_L1"
 "ma_L2"
 "sigma2_η"

julia> model.results.coef_table.coef
3-element Vector{Float64}:
 0.7612171821159301
 0.43638168954943535
 0.16763243467500588
```

**Comment by shayandavoodii** [comment]
Thank you for your kind response! So, this means it is not necessary to call `fit!` in order to get the coefficients. The only thing is that I'm not familiar with a notation of MA that uses $L$. I don't know how to match that with the notation I provided earlier.

**Comment by shayandavoodii** [comment]
I guess "ma_L1" and "ma_L2" refer to the MA (Moving Average) coefficients associated with the lagged error terms. Then, "ma_L1" represents the coefficient for the first lag of the error term, and "ma_L2" represents the coefficient for the second lag of the error term. Furthermore, "sigma2_η" represents the variance ($\sigma^2$) of the white noise error term ( $\epsilon_t$ ).

**Comment by raphaelsaavedra** [comment]
You do need to call `fit!`, otherwise the parameters won't have been estimated yet:

```julia
julia> model = SARIMA(ts, order=(0,0,2))
SARIMA(0, 0, 2)x(0, 0, 0, 0) with zero mean    

julia> model.results.coef_table
StateSpaceModels.CoefficientTable{Float64}(String[], Float64[], Float64[], Float64[], Float64[])

julia> StateSpaceModels.fit!(model)
SARIMA(0, 0, 2)x(0, 0, 0, 0) with zero mean    

julia> model.results.coef_table
StateSpaceModels.CoefficientTable{Float64}(["ma_L1", "ma_L2", "sigma2_η"], [0.7612171821159301, 0.43638168954943535, 0.16763243467500588], [0.09444579747538931, 0.11219079770386164, 0.028962339753974605], [8.05983116733477, 3.889638887329303, 5.787945176356171], [0.0, 0.0, 0.0])
```

I haven't looked at this particular code in a long time, but I believe the `L1` and `L2` refer to the MA lagged parameters. So `ma_L1` would be the first MA lagged parameter, and `ma_L2` would be the second MA lagged parameter.

**Comment by shayandavoodii** [comment]
Thank you so much. It means the world to me ❤

**Comment by raphaelsaavedra** [comment]
Happy to help!

**Comment by guilhermebodin** [comment]
As a comment, you can also call the function `print_results`

```julia
julia>  ts = rand(100);

julia> model = SARIMA(ts, order=(0,0,2))
SARIMA(0, 0, 2)x(0, 0, 0, 0) with zero mean

julia> res = StateSpaceModels.fit!(model)
SARIMA(0, 0, 2)x(0, 0, 0, 0) with zero mean

julia> print_results(model)
                             Results
===============================================================
Model:                        SARIMA(0, 0, 2)x(0, 0, 0, 0) with zero mean
Number of observations:       100
Number of unknown parameters: 3
Log-likelihood:               -58.5700
AIC:                          123.1401
AICc:                         123.3901
BIC:                          130.9556
---------------------------------------------------------------
Parameter      Estimate      Std.Error      z stat      p-value
ma_L1            0.5884         0.1198      4.9112       0.0000
ma_L2            0.3002         0.0987      3.0416       0.0000
sigma2_η         0.1880         0.0307      6.1302       0.0000
```

**Comment by shayandavoodii** [comment]
Thank you so much! It's a great summary!
