### ISSUE TITLE
Add `verbose` key argument

### ISSUE THREAD

**Issue by guilhermebodin** [LAMPSPUC/StateSpaceModels.jl#38]
I think there should be a `verbose` key argument to make progress logs optional.

**Comment by raphaelsaavedra** [comment]
Good point. We can have three levels: 0 outputs nothing, 1 outputs the `@info` and `@warning` logs from the model, 2 outputs everything including the optimization logs.

**Comment by raphaelsaavedra** [comment]
In this case, we can leave 1 as default.

**Comment by raphaelsaavedra** [comment]
Done in #40.
